version: 2

sources:
  - name: crosschain
    database: "{{ 'crosschain' if target.database == 'AURORA' else 'crosschain_dev' }}"
    schema: core
    tables:
      - name: dim_date_hours
      - name: address_tags
      - name: dim_dates

  - name: bronze_streamline
    database: streamline

    schema: |
      {{ "AURORA_DEV" if var("STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES", False) else "AURORA" }}
    tables:
      - name: blocks
      - name: transactions
      - name: tx_receipts
  - name: crosschain_silver
    database: crosschain

    schema: silver
    tables:
      - name: number_sequence
